### ISSUE TITLE
update a readme

### ISSUE THREAD

**Issue by lakshmankashyap** [AvanthikaMeenakshi/uthiramapp#2]
hi meenakshi,
please update a readme file better for user point of view on start project

**Comment by AvanthikaMeenakshi** [comment]
@lakshmankashyap, I have added the database dump and readme. In the client/public/blooddonar-template, you can find the template from which the project has been bootstrapped. I'm no longer developing it due to time constraints, I'll be happy if you are eager to continue it. Happy coding!

**Comment by lakshmankashyap** [comment]
no problem @AvanthikaMeenakshi
