### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by YPvenkat** [AvanthikaMeenakshi/uthiramapp#3]
Hi Meenakshi, can u pls
 provide the table structure of the Database

**Comment by NitinKalia** [comment]
Hi Meenakshi, can u pls
provide the table structure of the Database

**Comment by AvanthikaMeenakshi** [comment]
Hi @NitinKalia and @YPvenkat , I have added the database dump and readme. In the client/public/blooddonar-template, you can find the template from which the project is bootstrap. I'm no longer developing it due to time constraints, I'll be happy if you guys are eager to do. Happy coding!
