### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PassAssociates** [AvanthikaMeenakshi/uthiramapp#4]
Failed to compile
./src/index.js
Cannot find file: 'index.js' does not match the corresponding name on disk: '.\src\components\App\app'.
This error occurred during the build time and cannot be dismissed.

**Comment by ParkerSm1th** [comment]
Same issue

**Comment by AvanthikaMeenakshi** [comment]
Looking into it. Give me 30 minutes!

**Comment by ParkerSm1th** [comment]
Thanks :)

**Comment by ParkerSm1th** [comment]
> Looking into it. Give me 30 minutes!

Any updates?

**Comment by AvanthikaMeenakshi** [comment]
Can you add more steps for me to reproduce? i'm unable to reproduce this on my end.

**Comment by ParkerSm1th** [comment]
I've just attempted to run and it had this bug.

**Comment by AvanthikaMeenakshi** [comment]
Hi, thanks for reporting this, I've fixed this issue and have updated the instructions.

**Comment by AvanthikaMeenakshi** [comment]
Closing this issue as fixed.
