### ISSUE TITLE
Frontend not connected with MySQL server

### ISSUE THREAD

**Issue by Mylonymus** [AvanthikaMeenakshi/uthiramapp#7]
I was install both projects and execute first server, execute the sql in the db and the last step, execute the frontend project and not working the queries and list of pacients.

Please, do you could help me to run correctly?

Thanks!

**Comment by AvanthikaMeenakshi** [comment]
Do you have mysql installed? You need to import the sql file donorapp.sql. If you have windows, try installing xampp & import it via phpmyadmin.

Once you import your database into mysql, you need to replace host, username, password(if any) and db name in the following:

```
app.use(function(req, res, next) {
  res.locals.connection = mysql.createConnection({
    host     : 'your_host',
    user     : 'your_root',
    database : 'your_database_name',
    password: "your_password_here"
  });
  res.locals.connection.connect();
  next();
});
```

**Comment by miranaitamara** [comment]
I have already tried all these steps but I can not access the database, I think it's a backend problem!!

thanks

**Comment by AvanthikaMeenakshi** [comment]
@miranaitamara , I'm able to run it successfully, both the front-end and the back-end. The steps are the same as mentioned, make sure you have mysql up and running, and the configuration of the mysql server matches with the connection invoked. 

If you can paste my the exact error you're encountering, I can be of more help to you.

**Comment by miranaitamara** [comment]
@AvanthikaMeenakshi,  yeah it's good I found the error, however ("find donor" gives me that)
looks like this page dosen't exist..

**Comment by AvanthikaMeenakshi** [comment]
Yes, not all the pages are developed and ready for you. I've got the template in uthiramapp/frontend/public/blooddonar-template/ - Please take it from there and help yourself :) Thanks.
